name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Linting (Optional: Add eslint configuration to your project)
      - name: Run Linting
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm test

      # Build application (Optional: If you have a build step)
      - name: Build application
        run: npm run build

      # Deploy to the hosting environment (Optional)
      - name: Deploy application
        env:
          NODE_ENV: production
        run: |
          echo "Deployment process would go here..."
          # Add deployment scripts here (e.g., Docker build, upload to hosting, etc.)

      # Verify API Endpoints (Optional)
      - name: API Testing with Postman
        run: |
          echo "Running Postman API tests..."
          newman run path/to/your-postman-collection.json
