name: Node.js CI/CD on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify Node.js version
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Linting (Optional)
      - name: Run Linting
        run: npm run lint

      # Step 5: Run Tests
      - name: Run Tests
        run: npm test

      # Step 6: Build the Application (Optional)
      - name: Build Application
        run: npm run build

      # Step 7: API Endpoint Tests (Optional)
      - name: Run API Tests with Newman
        run: |
          echo "Running Postman API tests..."
          newman run path/to/your-postman-collection.json

      # Step 8: Deploy to Production (Optional)
      - name: Deploy Application
        env:
          NODE_ENV: production
        run: |
          echo "Deploying application..."
          # Add your deployment scripts or commands here
